finances/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myfinance.urls')),
]

myfinance/urls.py
from django.urls import path

from .views import index as iv
from .views import despesa as dv
from .views import receita as rv
from .views import relatorio as relv

urlpatterns = [
    path('', iv.index, name="index"),

    path('despesa/', dv.despesa, name="despesa"),
    path('despesa/<int:id_despesa>/', dv.despesaOp, name="despesaOp"),

    path('receita/', rv.receita, name="receita"),
    path('receita/<int:id_receita>/', rv.receitaOp, name="receitaOp"),

    path('relatorio/despesas', relv.despesas, name="relatorio_despesas"),
    path('relatorio/despesas/filtro', relv.despesasFiltro, name="relatorio_despesas_filtro"),
    path('relatorio/receitas', relv.receitas, name="relatorio_receitas"),
    path('relatorio/receitas/filtro', relv.receitasFiltro, name="relatorio_receitas_filtro")
]

myfinance/models.py
from django.db import models

# Create your models here.

myfinance/models/despesa.py
from django.db import models

class Despesa(models.Model):
    CLASSIFICACAO_CHOICES = (
        ('AG', 'Água'),
        ('AL', 'Alimentação'),
        ('AG', 'Aluguel'),
        ('EN', 'Energia'),
        ('LA', 'Lazer'),
        ('OU', 'Outros'),
        ('TE', 'Telecomunicações'),
        ('TR', 'Transporte')
    )

    FORMA_PAGAMENTO_CHOICES = (
        ('B', 'Boleto'),
        ('C', 'Crédito'),
        ('D', 'Débito'),
        ('M', 'Dinheiro'),
        ('P', 'Depósito'),
        ('O', 'Outros')
    )
    
    SITUACAO_CHOICES = (
        ('PG', 'Pago'),
        ('AP', 'A pagar')
    )
    
    classificacao = models.CharField(max_length=2, choices=CLASSIFICACAO_CHOICES, default='OU')
    data_pagamento = models.DateField(null=True)
    data_vencimento = models.DateField(null=False)
    descricao = models.CharField(max_length=255)
    formaPagamento = models.CharField(max_length=1, choices=FORMA_PAGAMENTO_CHOICES, default='O')
    situacao = models.CharField(max_length=2, choices=SITUACAO_CHOICES, default='AP')
    valor = models.DecimalField(null=False, max_digits=8, decimal_places=2)
    

myfinance/models/receita.py
from django.db import models

class Receita(models.Model):
    CLASSIFICACAO_CHOICES = (
        ('DT', 'Dívida de terceiros'),
        ('DO', 'Doação'),
        ('SA', 'Salário'),
        ('SP', 'Serviço prestado'),
        ('OU', 'Outros'),
        ('VE', 'Vendas')
    )

    FORMA_RECEBIMENTO_CHOICES = (
        ('B', 'Boleto'),
        ('C', 'Crédito'),
        ('D', 'Débito'),
        ('M', 'Dinheiro'),
        ('P', 'Depósito'),
        ('O', 'Outros')
    )
    
    SITUACAO_CHOICES = (
        ('PR', 'Recebido'),
        ('AR', 'A receber')
    )
    
    classificacao = models.CharField(max_length=2, choices=CLASSIFICACAO_CHOICES, default='OU')
    data_expectativa = models.DateField(null=False)
    data_recebimento = models.DateField(null=True)
    descricao = models.CharField(max_length=255)
    formaRecebimento = models.CharField(max_length=1, choices=FORMA_RECEBIMENTO_CHOICES, default='O')
    situacao = models.CharField(max_length=2, choices=SITUACAO_CHOICES, default='AR')
    valor = models.DecimalField(null=False, max_digits=8, decimal_places=2)
    

myfinance/views.py
from django.shortcuts import render

# Create your views here.

myfinance/views/despesa.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from datetime import date
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist

from ..models import Despesa

# GET: abre uma página para criar uma despesa
# POST: cria no banco uma nova despesa baseado nos dados do form
@require_http_methods(["GET", "POST"])   
@csrf_exempt
def despesa(request):
    if(request.method=="GET"):
        context = criaContextNovaDespesa()
        return render(request, 'despesa.html', context)
    elif(request.method=="POST"):
        salvaNovaDespesa(request)
        context = criaContextNovaDespesa()
        context["message"] = 'Despesa cadastrada com sucesso!'
        return render(request, 'despesa.html', context)


# GET: abre uma página para editar a despesa de ID = id_despesa
# POST: atualiza no banco a despesa de ID = id_despesa baseado nos dados do form
# DELETE: deleta do banco a despesa de ID = id_despesa, e retorna um JSON
@require_http_methods(["GET", "POST", "DELETE"])  
@csrf_exempt
def despesaOp(request, id_despesa):
    despesa = None
    try:
        despesa = Despesa.objects.get(id=id_despesa)
    except ObjectDoesNotExist:
        print(f"""Despesa não existe!""")

    if(request.method=="GET"):
        context = {}
        if(despesa):
            dtVencimento = '%s-%s-%s' % (despesa.data_vencimento.strftime("%Y"), despesa.data_vencimento.strftime("%m"), despesa.data_vencimento.strftime("%d"))
            despesa.data_vencimento = dtVencimento
            if(despesa.data_pagamento):
                dtPagamento = '%s-%s-%s' % (despesa.data_pagamento.strftime("%Y"), despesa.data_pagamento.strftime("%m"), despesa.data_pagamento.strftime("%d"))
                despesa.data_pagamento = dtPagamento
            
            context = initContextDespesa(despesa)

        return render(request, 'despesa.html', context)
    elif(request.method=="POST"):
        context = criaContextNovaDespesa()
        if(despesa):
            atualizaDespesa(request, id_despesa)
            context["message"] = 'Despesa atualizada com sucesso!'
            
        return render(request, 'despesa.html', context)
    elif(request.method=="DELETE"):
        jsonReturn = {"success" : False}
        if(despesa):
            despesa.delete()
            jsonReturn = {"success" : True}
        
        return JsonResponse(jsonReturn)

# inicializa o context vazio
def initContextDespesa(despesa):
    context = { 
        'despesa' : despesa,
        'classificacoes' : [],
        'formasPagamento' : [],
        'situacoes' : []
    }
    
    fieldsClassificacao = Despesa.CLASSIFICACAO_CHOICES
    for field, value in fieldsClassificacao:
        itemClassificacao = {"key" : field, "value" : value}
        context["classificacoes"].append(itemClassificacao)

    fieldsFormasPagamento = Despesa.FORMA_PAGAMENTO_CHOICES
    for field, value in fieldsFormasPagamento:
        itemFormaPagamento = {"key" : field, "value" : value}
        context["formasPagamento"].append(itemFormaPagamento)

    fieldsSituacoes = Despesa.SITUACAO_CHOICES
    for field, value in fieldsSituacoes:
        itemSituacao = {"key" : field, "value" : value}
        context["situacoes"].append(itemSituacao)
    
    return context

# cria o context para exibir na página de nova despesa
def criaContextNovaDespesa():
    dtToday = '%s-%s-%s' % (date.today().strftime("%Y"), date.today().strftime("%m"), date.today().strftime("%d"))
    despesa = Despesa(classificacao='OU',
                      data_pagamento='',
                      data_vencimento=dtToday,
                      descricao='',
                      formaPagamento='O',
                      situacao='AP',
                      valor=''
                    )
    context = initContextDespesa(despesa)
    return context

# salva as informações da nova despesa
def salvaNovaDespesa(request):
    valor = request.POST['valor']

    dataPagamento = request.POST['data_pagamento']
    if(dataPagamento == ""):
        dataPagamento = None

    despesa = Despesa(classificacao=request.POST['classificacao'],
                      data_pagamento=dataPagamento,
                      data_vencimento=request.POST['data_vencimento'],
                      descricao=request.POST['descricao'],
                      formaPagamento=request.POST['formaPagamento'],
                      situacao=request.POST['situacao'],
                      valor=valor
                    )

    despesa.save()

# atualiza as informações de uma despesa existente
def atualizaDespesa(request, id_despesa):
    valor = request.POST['valor']

    dataPagamento = request.POST['data_pagamento']
    if(dataPagamento == ""):
        dataPagamento = None

    despesa = Despesa(id=id_despesa,
                      classificacao=request.POST['classificacao'],
                      data_pagamento=dataPagamento,
                      data_vencimento=request.POST['data_vencimento'],
                      descricao=request.POST['descricao'],
                      formaPagamento=request.POST['formaPagamento'],
                      situacao=request.POST['situacao'],
                      valor=valor
                    )

    despesa.save()

myfinance/views/index.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt

from ..models import Conf, Despesa, Receita
import operator

@require_http_methods(["GET", "POST"])
@csrf_exempt
def index(request):
    if(request.method=="GET"):
        context = carregaContextFluxo()
        return render(request, 'index.html', context)
    elif(request.method=="POST"):
        result = Conf.objects.all()
        message = 'Saldo inicial criado com sucesso!'
        if(result.count() > 0):
            message = 'Saldo inicial alterado com sucesso!'
            for confObj in result:
                confObj.delete()

        conf = Conf(saldoInicial=request.POST['saldoInicial'])
        conf.save()
        context = carregaContextFluxo()
        context["message"] = message
        return render(request, 'index.html', context)

# carrega o context do fluxo de caixa
def carregaContextFluxo():
    saldoInicial = carregaSaldoInicial()
    context = {'saldoInicial' : saldoInicial}
    if(saldoInicial != None):
        saldoAtual = saldoInicial

        fluxo = initFluxo(saldoInicial)
        for periodo in fluxo:
            saldoAtual = fluxo[periodo]['saldoFinal']
            break

        context['fluxo'] = fluxo
        context['saldoAtual'] = saldoAtual

    return context

# se existir carrega o saldo inicial
def carregaSaldoInicial():
    saldoInicial = None
    searchSaldoInicial = Conf.objects.all()
    if(searchSaldoInicial.count() >= 1):
        saldoInicial = searchSaldoInicial[0].saldoInicial

    return saldoInicial

# inicializa e adiciona as informações do fluxo de caixa, com as informações de todos os meses
def initFluxo(saldoInicial):
    if(saldoInicial == None):
        return {}

    fluxo = {}
    fluxo = createOrderPeriodos(fluxo)
    fluxo = setResumoReceitas(fluxo)
    fluxo = setResumoDespesas(fluxo)
    fluxo = setSaldoIniFinLuc(fluxo, saldoInicial)
    fluxo = setDespesasOrder(fluxo)
    fluxo = setReceitasOrder(fluxo)
    fluxo = setSaldoAcumulado(fluxo, saldoInicial)

    return fluxo

# inicializa o fluxo de um mês vazio
def createFluxoVazio(fluxo, periodo):
    fluxo[periodo] = {  'saldoReceber' : 0, 
                        'saldoRecebido' : 0, 
                        'saldoPagar' : 0, 
                        'saldoPago' : 0,
                        'saldoInicial' : 0,
                        'saldoFinal' : 0,
                        'lucratividade' : 0,
                        'saldoPrevisto' : 0,
                        "receitas" : [],
                        "despesas" : []}
    return fluxo

# cria a ordem inversa dos periodos para ser apresentada na página
def createOrderPeriodos(fluxo):
    lstDates = []
    resultReceitas1 = Receita.objects.order_by('-data_recebimento')
    for receita in resultReceitas1:
        if(receita.data_recebimento):
            if(receita.data_recebimento not in lstDates):
                lstDates.append(receita.data_recebimento)

    resultReceitas2 = Receita.objects.order_by('-data_expectativa')
    for receita in resultReceitas2:
        if(receita.data_expectativa):
            if(receita.data_expectativa not in lstDates):
                lstDates.append(receita.data_expectativa)

    resultDespesas1 = Despesa.objects.order_by('-data_pagamento')
    for despesa in resultDespesas1:
        if(despesa.data_pagamento):
            if(despesa.data_pagamento not in lstDates):
                lstDates.append(despesa.data_pagamento)

    resultDespesas2 = Despesa.objects.order_by('-data_vencimento')
    for despesa in resultDespesas2:
        if(despesa.data_vencimento):
            if(despesa.data_vencimento not in lstDates):
                lstDates.append(despesa.data_vencimento)

    sorted_list = sorted(lstDates)
    for dateCheck in reversed(sorted_list):
        periodo = '%s/%s' % (dateCheck.strftime("%m"), dateCheck.strftime("%Y"))
        if periodo not in fluxo:
            fluxo = createFluxoVazio(fluxo, periodo)
    
    return fluxo

# recupera as seguintes informações do mês: saldo recebido, saldo a receber
def setResumoReceitas(fluxo):
    resultReceitas = Receita.objects.all().order_by('-data_expectativa')
    for receita in resultReceitas:
        if(receita.data_recebimento):
            periodo = '%s/%s' % (receita.data_recebimento.strftime("%m"), receita.data_recebimento.strftime("%Y"))
        else:
            periodo = '%s/%s' % (receita.data_expectativa.strftime("%m"), receita.data_expectativa.strftime("%Y"))

        if(receita.situacao == "PR"):
            fluxo[periodo]['saldoRecebido'] = fluxo[periodo]['saldoRecebido'] + receita.valor
        else:
            fluxo[periodo]['saldoReceber'] = fluxo[periodo]['saldoReceber'] + receita.valor

    return fluxo

# recupera as seguintes informações do mês: saldo pago, saldo a pagar
def setResumoDespesas(fluxo):
    resultDespesas = Despesa.objects.all().order_by('-data_vencimento')
    for despesa in resultDespesas:
        if(despesa.data_pagamento):
            periodo = '%s/%s' % (despesa.data_pagamento.strftime("%m"), despesa.data_pagamento.strftime("%Y"))
        else:
            periodo = '%s/%s' % (despesa.data_vencimento.strftime("%m"), despesa.data_vencimento.strftime("%Y"))
        
        if(despesa.situacao == "PG"):
            fluxo[periodo]['saldoPago'] = fluxo[periodo]['saldoPago'] + despesa.valor
        else:
            fluxo[periodo]['saldoPagar'] = fluxo[periodo]['saldoPagar'] + despesa.valor

    return fluxo

# recupera as seguintes informações do mês: saldo inicial, saldo final, lucratividade, saldo previsto
def setSaldoIniFinLuc(fluxo, saldoInicial):
    setSaldoInicial = False
    saldoFinalMesAnterior = 0
    for periodo in reversed(fluxo):
        if(not setSaldoInicial):
            fluxo[periodo]['saldoInicial'] =  saldoInicial
            setSaldoInicial = True
        else:
            fluxo[periodo]['saldoInicial'] =  saldoFinalMesAnterior

        fluxo[periodo]['saldoFinal'] = fluxo[periodo]['saldoInicial'] + fluxo[periodo]['saldoRecebido'] - fluxo[periodo]['saldoPago']
        fluxo[periodo]['lucratividade'] = fluxo[periodo]['saldoFinal'] - fluxo[periodo]['saldoInicial']
        saldoFinalMesAnterior = fluxo[periodo]['saldoFinal']
        fluxo[periodo]['saldoPrevisto'] = fluxo[periodo]['saldoFinal'] + fluxo[periodo]['saldoReceber'] - fluxo[periodo]['saldoPagar']
    
    return fluxo

# coloca as receitas em ordem por classificação
def setReceitasOrder(fluxo):
    receitas = list(Receita.objects.all())
    receitas.sort(key=operator.methodcaller('get_classificacao_display'))
    for receita in receitas:
        periodo = '%s/%s' % (receita.data_expectativa.strftime("%m"), receita.data_expectativa.strftime("%Y"))
        dtExpectativa = '%s/%s/%s' % (receita.data_expectativa.strftime("%d"), receita.data_expectativa.strftime("%m"), receita.data_expectativa.strftime("%Y"))
        receita.data_expectativa = dtExpectativa
        if(receita.data_recebimento):
            periodo = '%s/%s' % (receita.data_recebimento.strftime("%m"), receita.data_recebimento.strftime("%Y"))
            dtrecebimento = '%s/%s/%s' % (receita.data_recebimento.strftime("%d"), receita.data_recebimento.strftime("%m"), receita.data_recebimento.strftime("%Y"))
            receita.data_recebimento = dtrecebimento

        fluxo[periodo]['receitas'].append(receita)

    return fluxo

# coloca as despesas em ordem por classificação
def setDespesasOrder(fluxo):
    despesas = list(Despesa.objects.all())
    despesas.sort(key=operator.methodcaller('get_classificacao_display'))
    for despesa in despesas:
        periodo = '%s/%s' % (despesa.data_vencimento.strftime("%m"), despesa.data_vencimento.strftime("%Y"))
        dtVencimento = '%s/%s/%s' % (despesa.data_vencimento.strftime("%d"), despesa.data_vencimento.strftime("%m"), despesa.data_vencimento.strftime("%Y"))
        despesa.data_vencimento = dtVencimento
        if(despesa.data_pagamento):
            periodo = '%s/%s' % (despesa.data_pagamento.strftime("%m"), despesa.data_pagamento.strftime("%Y"))
            dtpagamento = '%s/%s/%s' % (despesa.data_pagamento.strftime("%d"), despesa.data_pagamento.strftime("%m"), despesa.data_pagamento.strftime("%Y"))
            despesa.data_pagamento = dtpagamento
        
        fluxo[periodo]['despesas'].append(despesa)

    return fluxo

# adiciona para cada despesa paga e cada receita recebida, o saldo acumulado
def setSaldoAcumulado(fluxo, saldoInicial):
    valorAcumulado = saldoInicial
    for periodo in reversed(fluxo):
        for despesa in reversed(fluxo[periodo]['despesas']):
            if(despesa.situacao == "PG"):
                valorAcumulado = valorAcumulado - despesa.valor
                despesa.saldoAcumulado = valorAcumulado
        for receita in reversed(fluxo[periodo]['receitas']):
            if(receita.situacao == "PR"):
                valorAcumulado = valorAcumulado + receita.valor
                receita.saldoAcumulado = valorAcumulado

    return fluxo

myfinance/templates/relatorioDespesas.html
<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>MY FINANCES</title>
</head>

<body style="background-color: #c9d6df">
    <div class="container">
        <h1 style="color:#cf7500; text-align: center; margin-bottom: 3%; margin-top: 3%;">MY FINANCES</h1>

        <ul class="nav justify-content-center nav-pills">
            <li class="nav-item border" style="background-color: #52616b; border-radius: 10px;">
                <a class="nav-link" href="/">
                    <h4 style="color: #f0a500;">Fluxo de caixa</h4>
                </a>
            </li>
            <li class="nav-item border" style="background-color: #52616b; border-radius: 10px;">
                <a class="nav-link" href="/despesa/">
                    <h4 style="color: #f0a500;">Nova despesa</h4>
                </a>
            </li>
            <li class="nav-item border" style="background-color: #52616b; border-radius: 10px;">
                <a class="nav-link" href="/receita/">
                    <h4 style="color: #f0a500;">Nova receita</h4>
                </a>
            </li>
            <li class="nav-item" style="background-color: #f0a500; border-radius: 10px;">
                <a class="nav-link " href="/relatorio/despesas">
                    <h4 style="color: #52616b;">Contas a pagar</h4>
                </a>
            </li>
            <li class="nav-item border" style="background-color: #52616b; border-radius: 10px;">
                <a class="nav-link" href="/relatorio/receitas">
                    <h4 style="color: #f0a500;">Contas a receber</h4>
                </a>
            </li>
        </ul>


        <div class="border rounded p-3 mb-5" style="background-color: #52616b; margin-top: 3%; color: #f0a500;">
            <h4 class="mt-3" style="text-align: center;">Relatório - Contas a pagar</h4>
            <div class="border rounded p-3 mb-5" style="margin-top: 3%;">
                <form action="/relatorio/despesas/filtro" method="post" class="mt-4 mb-3">
                    <h6>Data de Vencimento:</h6>
                    <div class="form-row mt-3">
                        <input type="date" class="form-control-sm col-sm-2" id="inputDate" name="data_filtro"
                            value="{{dateMax}}" required>
                        <button type="submit" class="btn btn-dark btn-sm ml-2 col-sm-1">Filtrar</button>
                    </div>
                </form>
                {% if despesas %}
                <button type="button" class="btn btn-dark mb-1 mt-3">
                    Quantidade <span class="badge badge-light">{{ despesas|length }}</span>
                </button>
                <table class="table table-bordered table-striped table-sm" id="tableRelatorio">
                    <thead>
                        <tr class="bg-dark text-white">
                            <th scope="col" style="width: 15%">Data de Vencimento</th>
                            <th scope="col" style="width: 25%">Descrição</th>
                            <th scope="col" style="width: 15%">Classificação</th>
                            <th scope="col" style="width: 15%">Forma de Pagamento</th>
                            <th scope="col" style="width: 10%">Valor (R$)</th>
                        </tr>
                    </thead>
                    <tbody class="table-light">
                        {% for despesa in despesas %}
                        <tr>
                            <td>{{despesa.data_vencimento}}</td>
                            <td>{{despesa.descricao}}</td>
                            <td>{{despesa.get_classificacao_display}}</td>
                            <td>{{despesa.get_formaPagamento_display}}</td>
                            <td>{{despesa.valor}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="d-flex justify-content-end">
                    <button type="button" class="btn mb-1 mt-1 font-weight-bold"
                        style="background-color: #c9d6df; color: red">
                        Valor total a pagar <span class="badge badge-light">R$ {{ valorTotal }}</span>
                    </button>
                </div>
                {% else %}
                <div class="d-flex justify-content-left">
                    <h6 style="color: #c9d6df">Não existem contas pendentes até a data {{dateMaxBr}}</h6>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</body>

</html>

myfinance/templates/relatorioReceitas.html
<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>MY FINANCES</title>
</head>

<body style="background-color: #c9d6df">
    <div class="container">
        <h1 style="color:#cf7500; text-align: center; margin-bottom: 3%; margin-top: 3%;">MY FINANCES</h1>

        <ul class="nav justify-content-center nav-pills">
            <li class="nav-item border" style="background-color: #52616b; border-radius: 10px;">
                <a class="nav-link" href="/">
                    <h4 style="color: #f0a500;">Fluxo de caixa</h4>
                </a>
            </li>
            <li class="nav-item border" style="background-color: #52616b; border-radius: 10px;">
                <a class="nav-link" href="/despesa/">
                    <h4 style="color: #f0a500;">Nova despesa</h4>
                </a>
            </li>
            <li class="nav-item border" style="background-color: #52616b; border-radius: 10px;">
                <a class="nav-link" href="/receita/">
                    <h4 style="color: #f0a500;">Nova receita</h4>
                </a>
            </li>
            <li class="nav-item border" style="background-color: #52616b; border-radius: 10px;">
                <a class="nav-link" href="/relatorio/despesas">
                    <h4 style="color: #f0a500;">Contas a pagar</h4>
                </a>
            </li>
            <li class="nav-item border" style="background-color: #f0a500; border-radius: 10px;">
                <a class="nav-link" href="/relatorio/receitas">
                    <h4 style="color: #52616b;">Contas a receber</h4>
                </a>
            </li>
        </ul>

        <div class="border rounded p-3 mb-5" style="background-color: #52616b; margin-top: 3%; color: #f0a500;">
            <h4 class="mt-3" style="text-align: center;">Relatório - Contas a receber</h4>
            <div class="border rounded p-3 mb-5" style="margin-top: 3%;">
                <form action="/relatorio/receitas/filtro" method="post" class="mt-4 mb-3">
                    <h6>Data de Expectativa:</h6>
                    <div class="form-row mt-3">
                        <input type="date" class="form-control-sm col-sm-2" id="inputDate" name="data_filtro"
                            value="{{dateMax}}" required>

                        <button type="submit" class="btn btn-dark btn-sm ml-2 col-sm-1">Filtrar</button>
                    </div>
                </form>
                {% if receitas %}
                <button type="button" class="btn btn-dark mb-1 mt-3">
                    Quantidade <span class="badge badge-light">{{ receitas|length }}</span>
                </button>
                <table class="table table-bordered table-striped table-sm" id="tableRelatorio">
                    <thead>
                        <tr class="bg-dark text-white">
                            <th scope="col" style="width: 15%">Data de Expectativa</th>
                            <th scope="col" style="width: 25%">Descrição</th>
                            <th scope="col" style="width: 15%">Classificação</th>
                            <th scope="col" style="width: 15%">Forma de Recebimento</th>
                            <th scope="col" style="width: 10%">Valor (R$)</th>
                        </tr>
                    </thead>
                    <tbody class="table-light">
                        {% for receita in receitas %}
                        <tr>
                            <td>{{receita.data_expectativa}}</td>
                            <td>{{receita.descricao}}</td>
                            <td>{{receita.get_classificacao_display}}</td>
                            <td>{{receita.get_formaRecebimento_display}}</td>
                            <td>{{receita.valor}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="d-flex justify-content-end">
                    <button type="button" class="btn mb-1 mt-1 font-weight-bold"
                        style="background-color: #c9d6df; color: green">
                        Valor total a receber <span class="badge badge-light">R$ {{ valorTotal }}</span>
                    </button>
                </div>
                {% else %}
                <div class="d-flex justify-content-left">
                    <h6 style="color: #c9d6df">Não existem contas a receber até a data {{dateMaxBr}}</h6>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</body>

</html>